# Numerické výpočty a vizualizace pomocí NumPy a Matplotlib

**NumPy** je základní knihovna Python-u pro práci s numerickými daty, konkrétně s 1- až n-rozměrnými maticemi
a poskytuje pro ně základní operace. Chceme-li použít `numpy`, je samozřejmě nutné modul importovat. Pro interaktivní použití se často importuje vše pomocí

In [1]:
from numpy import *

Jinak se obvykle používá

In [2]:
import numpy as np

## IPython pylab
Můžeme také použít prostředí pylab, které oba importy provede. Navíc importuje také grafickou knihovnu matplotlib, kterou blíže představíme později.

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Vytváříme `numpy` pole (`array`)
Základním typem je pole `numpy.ndarray`. Existuje několik způsobů, jak vytvořit nové numpy pole.

* z jiného objektu Python-u, nejčastěji typu seznam (list) nebo tuple
* pomocí funkce numpy, která generuje array, např. zeros nebo arange
* nebo načtením ze souboru

### Ze seznamu
Na seznam použijeme funkci `array`.

In [4]:
a = array([1,2,3,4,5])

Matice se vytvoří z vnořeného seznamu.

In [5]:
M = array([[1, 2], [3, 4]])
print(M)

[[1 2]
 [3 4]]


`a` and `M` jsou oboje typu `ndarray`.

In [6]:
type(a), type(M)

(numpy.ndarray, numpy.ndarray)

Základní vlastnosti polí se volají přes tvz. tečkovou notaci.

* `ndarray.ndim` dimenze neboli rank pole
* `ndarray.shape` vrací N-tici indikující rozměry pole. Pro matici s n řádkama a m sloupcema, bude 'shape' (n,m)
* `size` celkový počet elementů v poli

In [7]:
a.shape

(5,)

In [8]:
M.shape

(2, 2)

In [9]:
a.size

5

In [10]:
M.size

4

In [11]:
a.ndim

1

In [12]:
M.ndim

2

### Pomocné generátory polí
Zejména velká pole by bylo nepraktické inicializovat pomocí seznamů. Naštěstí v numpy existují [funkce](http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html), které generují typická pole.

**`arange`** vygeneruje posloupnost s daným krokem

In [13]:
arange(-1, 7, 0.5)  # argumenty: start, stop, krok

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,
        4.5,  5. ,  5.5,  6. ,  6.5])

**`linspace`** a **`logspace`** vytváří posloupnosti s daným počtem prvků.

In [14]:
# první a poslední prvek jsou obsaženy ve výsledku
linspace(0, 10, 9)

array([  0.  ,   1.25,   2.5 ,   3.75,   5.  ,   6.25,   7.5 ,   8.75,  10.  ])

In [15]:
logspace(0, 10, 6, base=10)

array([  1.00000000e+00,   1.00000000e+02,   1.00000000e+04,
         1.00000000e+06,   1.00000000e+08,   1.00000000e+10])

**`ones`** a **`zeros`** vytvoří pole ze samých nul nebo jedniček.

In [16]:
ones(3)

array([ 1.,  1.,  1.])

In [17]:
# pokud chceme 2 a více rozměrů, musíme zadat rozměr jako tuple
zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

**`meshgrid`** tvoří pravidelnou mříž.

In [18]:
x, y = meshgrid([0,1,2,3], [6,7,8])
print(x)
print(y)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]


Náhodná data vytvoří funkce **`rand`** a další z modulu **`random`**.

In [19]:
# několik náhodných čísel [0, 1] s rovnoměrným rozdělením
random.rand(4)

array([ 0.5942576 ,  0.2696658 ,  0.78005872,  0.10535556])

In [20]:
# matice s náhodnými čísly z normálním rozdělením
random.randn(4,4)

array([[-0.51952465, -0.6677667 , -0.57013976, -0.68173649],
       [ 1.33035633, -1.73217159, -0.19329447,  0.67478742],
       [-0.45602389, -0.24492823,  0.68175259, -1.06422298],
       [-0.07506621, -0.89728951, -0.75077749, -1.31504301]])

**`diag`** vytvoří diagonální matici, případně vrátí diagonálu matice.

In [21]:
# diagonální matice
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
# vrátí diagonálu jako vektor
diag(diag([1,2,3]))

array([1, 2, 3])

In [23]:
from mystyle import css_styling
css_styling()